<a href="https://colab.research.google.com/github/pedro07br/portfolio-python-analytics/blob/main/Atividade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a = input("Digite um número inteiro: ")
b = input("Digite um número inteiro: ")
c = input("Digite um número decimal: ")

soma = int(a) + int(b) + float(c)

if int(a) > int(b):
    somaDecimal = int(a) / float(c)
else:
    somaDecimal = int(b) / float(c)

somaDecimal = round(somaDecimal, 2)

print("A soma total é:", soma)
print("A divisão do maior número inteiro pelo decimal é:", somaDecimal)


Digite um número inteiro: 12
Digite um número inteiro: 12
Digite um número decimal: 12
A soma total é: 36.0
A divisão do maior número inteiro pelo decimal é: 1.0


In [ ]:
import numpy as np

d1 = np.array([2, 4, 6, 8, 10])
d2 = np.array([1, 3, 5, 7, 9])

print("d1 - shape:", d1.shape)
print("d1 - dimensões:", d1.ndim)
print("d1 - tipo de dados:", d1.dtype)

print("d2 - shape:", d1.shape)
print("d2 - dimensões:", d1.ndim)
print("d2 - tipo de dados:", d1.dtype)

soma = d1 + d2
produto = d1 * d2
media_soma = np.mean(soma)

print("Soma elemento a elemento:", soma)
print("Produto elemento a elemento:", produto)
print("Média da soma:", media_soma)

matriz = np.arange(1, 10).reshape(3, 3)
print("Matriz 3x3:\n", matriz)

soma_linhas = np.sum(matriz, axis=1)
soma_colunas = np.sum(matriz, axis=0)
transposta = matriz.T

print("Soma por linha:", soma_linhas)
print("Soma por coluna:", soma_colunas)
print("Matriz transposta:\n", transposta)


d1 - shape: (5,)
d1 - dimensões: 1
d1 - tipo de dados: int64
d2 - shape: (5,)
d2 - dimensões: 1
d2 - tipo de dados: int64
Soma elemento a elemento: [ 3  7 11 15 19]
Produto elemento a elemento: [ 2 12 30 56 90]
Média da soma: 11.0
Matriz 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Soma por linha: [ 6 15 24]
Soma por coluna: [12 15 18]
Matriz transposta:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [20]:
import numpy as np

x = np.linspace(0, 1, 20)

y = 3*x**2 - 2*x + 1

print("x:", x)
print("y:", y)

y_norm = (y - np.min(y)) / (np.max(y) - np.min(y))

print("y_norm:", y_norm)

mask = y_norm > 0.5
print("Máscara booleana:", mask)

subset = y_norm[mask]
print("Tamanho do subconjunto:", subset.size)
print("Três primeiros valores selecionados:", subset[:3])

x: [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
y: [1.         0.90304709 0.82271468 0.75900277 0.71191136 0.68144044
 0.66759003 0.67036011 0.68975069 0.72576177 0.77839335 0.84764543
 0.93351801 1.03601108 1.15512465 1.29085873 1.4432133  1.61218837
 1.79778393 2.        ]
y_norm: [0.24948025 0.17671518 0.11642412 0.06860707 0.03326403 0.01039501
 0.         0.002079   0.01663202 0.04365904 0.08316008 0.13513514
 0.1995842  0.27650728 0.36590437 0.46777547 0.58212058 0.70893971
 0.84823285 1.        ]
Máscara booleana: [False False False False False False False False False False False False
 False False False False  True  True  True  True]
Tamanho do subconjunto: 4
Três primeiros valores selecionados: [0.58212058 0.70893971 0.84823285]


In [50]:
import pandas as pd

data = {"Nome": ["Anay", "Pedro", "João", "Matheus"],
        "Prova01": [8.5, 7.0, 9.2, 9.7],
        "Prova02": [3.1, 6.0, 7.2, 9.8],
        "faltas":  [4, 2, 3, 1] }

df = pd.DataFrame(data)

print(df,"\n")
print(df.head(2),"\n")
print(df.info(),"\n")
print(df.describe(),"\n")


df["Media"] = df[["Prova01", "Prova02"]].mean(axis=1)
print(df,"\n")

df["Aprovado"] = df["Media"] >= 6
print(df,"\n")

df["Aprovada por presença"] = df["faltas"] <= 3
print(df,"\n")

aprovados = df[df["Aprovado"] & df["Aprovada por presença"]]

aprovados = aprovados.sort_values(by="Media", ascending=False)

resultado = aprovados[["Nome", "Media"]]

print(resultado)


      Nome  Prova01  Prova02  faltas
0     Anay      8.5      3.1       4
1    Pedro      7.0      6.0       2
2     João      9.2      7.2       3
3  Matheus      9.7      9.8       1 

    Nome  Prova01  Prova02  faltas
0   Anay      8.5      3.1       4
1  Pedro      7.0      6.0       2 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Nome     4 non-null      object 
 1   Prova01  4 non-null      float64
 2   Prova02  4 non-null      float64
 3   faltas   4 non-null      int64  
dtypes: float64(2), int64(1), object(1)
memory usage: 260.0+ bytes
None 

        Prova01   Prova02    faltas
count  4.000000  4.000000  4.000000
mean   8.600000  6.525000  2.500000
std    1.174734  2.780138  1.290994
min    7.000000  3.100000  1.000000
25%    8.125000  5.275000  1.750000
50%    8.850000  6.600000  2.500000
75%    9.325000  7.850000  3.250000
max    9.700000 

In [52]:
import pandas as pd
import numpy as np

# Simulando dados de vendas
data = {
    "Vendedor": [
        "Anny", "Pedro", "João", "Maria", "Lucas",
        "Anny", "Pedro", "João", "Maria", "Lucas",
        "Anny", "Pedro", "João", "Maria", "Lucas",
        "Anny", "Pedro", "João", "Maria", "Lucas"
    ],
    "Região": [
        "Norte", "Sul", "Leste", "Oeste", "Norte",
        "Sul", "Leste", "Oeste", "Norte", "Sul",
        "Leste", "Oeste", "Norte", "Sul", "Leste",
        "Oeste", "Norte", "Sul", "Leste", "Oeste"
    ],
    "Valor": np.random.uniform(100, 1000, 20),
    "Data": pd.date_range(start="2025-08-01", periods=20).strftime("%Y-%m-%d")
}

df = pd.DataFrame(data)

print("=== DataFrame de Vendas ===")
print(df, "\n")

regiao_totais = df.groupby("Região")["Valor"].sum()
regiao_medias = df.groupby("Região")["Valor"].mean()

regiao_top = regiao_totais.idxmax()
total_top_regiao = regiao_totais.max()

vendedor_totais = df.groupby("Vendedor")["Valor"].sum()
vendedor_top = vendedor_totais.idxmax()
valor_top_vendedor = vendedor_totais.max()

top3_vendedores = vendedor_totais.sort_values(ascending=False).head(3)

print("=== Total vendido por Região ===")
print(regiao_totais, "\n")

print("=== Média por venda por Região ===")
print(regiao_medias, "\n")

print("=== Top 3 Vendedores ===")
print(top3_vendedores, "\n")

print(f"=== Melhor vendedor do período: {vendedor_top} com faturamento de {valor_top_vendedor:.2f} ===")
print(f"=== Região com maior total vendido: {regiao_top} com total de {total_top_regiao:.2f} ===")


=== DataFrame de Vendas ===
   Vendedor Região       Valor        Data
0      Anny  Norte  764.961999  2025-08-01
1     Pedro    Sul  519.063704  2025-08-02
2      João  Leste  680.620698  2025-08-03
3     Maria  Oeste  805.045021  2025-08-04
4     Lucas  Norte  207.506466  2025-08-05
5      Anny    Sul  316.585147  2025-08-06
6     Pedro  Leste  698.010644  2025-08-07
7      João  Oeste  404.282622  2025-08-08
8     Maria  Norte  261.275027  2025-08-09
9     Lucas    Sul  164.420861  2025-08-10
10     Anny  Leste  667.648100  2025-08-11
11    Pedro  Oeste  870.164557  2025-08-12
12     João  Norte  993.681288  2025-08-13
13    Maria    Sul  296.695749  2025-08-14
14    Lucas  Leste  443.634986  2025-08-15
15     Anny  Oeste  981.940762  2025-08-16
16    Pedro  Norte  602.315940  2025-08-17
17     João    Sul  152.038131  2025-08-18
18    Maria  Leste  650.274203  2025-08-19
19    Lucas  Oeste  126.682975  2025-08-20 

=== Total vendido por Região ===
Região
Leste    3140.188631
Norte 